# https://wiki.hypr.land/Configuring/

#######################################
#           ┳┳┓    •                  #
#           ┃┃┃┏┓┏┓┓╋┏┓┏┓             #
#           ┛ ┗┗┛┛┗┗┗┗┛┛              #
monitor = DP-3, 1920x1080@144, 0x0, 1 #


##############################################################
#                     ┏┓                                     #
#                     ┃┃┏┓┏┓┏┓┏┓┏┓┏┳┓┏                       #
#                     ┣┛┛ ┗┛┗┫┛ ┗┻┛┗┗┛                       #
#                            ┛                               #
source = ~/.config/hypr/Programs&Enviroment/autostart.conf   #
source = ~/.config/hypr/Programs&Enviroment/environment.conf #
source = ~/.config/hypr/Programs&Enviroment/programs.conf    #

#################################################
#                 ┓┏•     ┓                     #
#                 ┃┃┓┏┓┏┏┓┃┏                    #
#                 ┗┛┗┛┗┻┗┻┗┛                    #
source = ~/.config/hypr/Visuals/animations.conf #
source = ~/.config/hypr/Visuals/look.conf       #

#############################################
#                ┳                          #
#                ┃┏┓┏┓┓┏╋                   #
#                ┻┛┗┣┛┗┻┗                   #
#                   ┛                       #
source = ~/.config/hypr/Input/keybinds.conf #
source = ~/.config/hypr/Input/keyboard.conf #



# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

layerrule = blur, wofi

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
