# Polkit, Interface para acesso SUDO.
exec-once = systemctl --user start hyprpolkitagent

# Papel de parede
exec-once = hyprpaper -c ~/.config/hypr/Utilities/hyprpaper.conf

# Cliphist, Gerenciador Clipboard
exec-once = wl-paste --type text --watch cliphist store # Guarda apenas texto 
exec-once = wl-paste --type image --watch cliphist store # Guarda imagens 
